<a href="https://colab.research.google.com/github/MohuaSinha/EVA4/blob/master/S15A/Dataset_Statistics_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
import time
import glob
import torch
import os

from IPython.display import Image, clear_output 
print('PyTorch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

PyTorch 1.5.0+cu101 _CudaDeviceProperties(name='Tesla K80', major=3, minor=7, total_memory=11441MB, multi_processor_count=13)


In [0]:
#Extract data
import zipfile
#for i in range(5):
archive = zipfile.ZipFile(f'/content/gdrive/My Drive/Colab Notebooks/EVA4/S14_15/image_dataset.zip')
archive.extractall()

In [0]:
#calculate STd and Mean
from tqdm import notebook
from PIL import Image
import numpy as np
def mean_std(path):

    n = 0
    s = np.zeros(3)
    sq = np.zeros(3)
    start = 0
    stop = 80000
    for part in range(5):
      print(f"from {start} to {stop} of set {part+1}")
      for i in notebook.tqdm(range(start,stop)):
          
            img = Image.open(f'/content/dataset{path}{str(i+1)}.jpg')
            x = np.array(img)/255
            s += x.sum(axis=(0,1))
            sq += np.sum(np.square(x), axis=(0,1))
            n += x.shape[0]*x.shape[1]
      start += 80000
      stop+=80000


    mu = s/n
    std = np.sqrt((sq/n - np.square(mu)))
    print(mu, sq/n, std, n)

In [5]:
mean_std(path ="/image/fg_bg_")

from 0 to 80000 of set 1



from 80000 to 160000 of set 2



from 160000 to 240000 of set 3



from 240000 to 320000 of set 4



from 320000 to 400000 of set 5



[0.50169254 0.51531572 0.38720035] [0.31468072 0.3239949  0.23126339] [0.25096876 0.2417532  0.28520041] 19360000000


In [6]:
mean_std(path ="/mask/fg_bg_mask_")

from 0 to 80000 of set 1



from 80000 to 160000 of set 2



from 160000 to 240000 of set 3



from 240000 to 320000 of set 4



from 320000 to 400000 of set 5



[0.09301607 0.09301607 0.09301607] [0.08978378 0.08978378 0.08978378] [0.28483643 0.28483643 0.28483643] 19360000000


In [7]:
mean_std(path ="/depthmap/depth_" )

from 0 to 80000 of set 1



from 80000 to 160000 of set 2



from 160000 to 240000 of set 3



from 240000 to 320000 of set 4



from 320000 to 400000 of set 5



[0.34092307 0.34092307 0.34092307] [0.17094507 0.17094507 0.17094507] [0.23391564 0.23391564 0.23391564] 19360000000


In [8]:
!du -h  --apparent-size "/content/dataset" # human understandable form

2.5G	/content/dataset/image
481M	/content/dataset/depthmap
516M	/content/dataset/mask
3.5G	/content/dataset
